// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: 3d_printer

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void OpaOn_Animation(lv_obj_t * TargetObject, int delay);
void OpaOff_Animation(lv_obj_t * TargetObject, int delay);
void ScreenIn_Animation(lv_obj_t * TargetObject, int delay);
void MenuIn_Animation(lv_obj_t * TargetObject, int delay);
void MenuOut_Animation(lv_obj_t * TargetObject, int delay);
void ScreenOut_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Screen_1_Print
void ui_Screen_1_Print_screen_init(void);
lv_obj_t * ui_Screen_1_Print;
lv_obj_t * ui_Background;
lv_obj_t * ui_Panel_Header;
lv_obj_t * ui_Label_Header;
lv_obj_t * ui_IMG_Wifi;
lv_obj_t * ui_IMG_PC;
lv_obj_t * ui_IMG_USB;
lv_obj_t * ui_BTN_Menu_Print_S1;
void ui_event_BTN_Menu_Move_S1(lv_event_t * e);
lv_obj_t * ui_BTN_Menu_Move_S1;
void ui_event_BTN_Menu_Setting_S1(lv_event_t * e);
lv_obj_t * ui_BTN_Menu_Setting_S1;
lv_obj_t * ui_S1_Content_Panel;
void ui_event_Slider_Print_View(lv_event_t * e);
lv_obj_t * ui_Slider_Print_View;
lv_obj_t * ui_Number_Print;
lv_obj_t * ui_Display_Time_S1;
lv_obj_t * ui_DT1;
lv_obj_t * ui_Label_Printing_Time_1;
lv_obj_t * ui_IMG_Tine_1;
lv_obj_t * ui_Label_Time_1;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_DT2;
lv_obj_t * ui_Label_Printing_Time_2;
lv_obj_t * ui_IMG_Tine_2;
lv_obj_t * ui_Label_Time_2;
lv_obj_t * ui_Display_Heat_S1;
lv_obj_t * ui_DT3;
lv_obj_t * ui_Label_Printing_Head_Temp;
lv_obj_t * ui_IMG_Head;
lv_obj_t * ui_Label_Head_Temp;
lv_obj_t * ui_Label_Printing_Head_Temp_2;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_DT3_copy;
lv_obj_t * ui_Label_Printing_Bed_Temp;
lv_obj_t * ui_IMG_Head1;
lv_obj_t * ui_Label_Bed_Temp;
lv_obj_t * ui_Label_Printing_Bed_Temp1;
lv_obj_t * ui_Panel_Buttons_S1;
lv_obj_t * ui_BTN_Pause;
lv_obj_t * ui_BTN_Pause_Top;
lv_obj_t * ui_Image_Pause;
lv_obj_t * ui_BTN_Cancel;
void ui_event_BTN_Cancel_Top(lv_event_t * e);
lv_obj_t * ui_BTN_Cancel_Top;
lv_obj_t * ui_Image_Cancel;


// SCREEN: ui_Screen_2_Move
void ui_Screen_2_Move_screen_init(void);
lv_obj_t * ui_Screen_2_Move;
lv_obj_t * ui_Background1;
lv_obj_t * ui_Panel_Header1;
lv_obj_t * ui_Label_Header1;
lv_obj_t * ui_IMG_Wifi1;
lv_obj_t * ui_IMG_PC1;
lv_obj_t * ui_IMG_USB1;
void ui_event_BTN_Menu_Print_S2(lv_event_t * e);
lv_obj_t * ui_BTN_Menu_Print_S2;
lv_obj_t * ui_BTN_Menu_Move_S2;
void ui_event_BTN_Menu_Setting_S2(lv_event_t * e);
lv_obj_t * ui_BTN_Menu_Setting_S2;
lv_obj_t * ui_S1_Content_Panel1;
lv_obj_t * ui_Display_Pos_XY;
lv_obj_t * ui_DP1;
lv_obj_t * ui_Label_X_Position;
lv_obj_t * ui_Label_X_Position_Number;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_DP2;
lv_obj_t * ui_Label_Y_Position;
lv_obj_t * ui_Label_Time_3;
lv_obj_t * ui_Display_Pos_y;
lv_obj_t * ui_DP3;
lv_obj_t * ui_Label_Z_Position;
lv_obj_t * ui_Label_Z_Position_Number;
lv_obj_t * ui_BTN_Move_Z;
void ui_event_GLOW_1(lv_event_t * e);
lv_obj_t * ui_GLOW_1;
void ui_event_GLOW_2(lv_event_t * e);
lv_obj_t * ui_GLOW_2;
lv_obj_t * ui_BTN_Image_Top;
lv_obj_t * ui_Label_Z_Position_2;
lv_obj_t * ui_Arrow_Z_up;
lv_obj_t * ui_Arrow_Z_Down;
lv_obj_t * ui_BTN_Move_XY;
void ui_event_GLOW_3(lv_event_t * e);
lv_obj_t * ui_GLOW_3;
void ui_event_GLOW_4(lv_event_t * e);
lv_obj_t * ui_GLOW_4;
void ui_event_GLOW_5(lv_event_t * e);
lv_obj_t * ui_GLOW_5;
void ui_event_GLOW_6(lv_event_t * e);
lv_obj_t * ui_GLOW_6;
lv_obj_t * ui_BTN_Move_XY_Top;
lv_obj_t * ui_Label_XY_Position;
lv_obj_t * ui_Arrow_Up_2;
lv_obj_t * ui_Arrow_Down_2;
lv_obj_t * ui_Arrow_Left_2;
lv_obj_t * ui_Arrow_Right_2;
lv_obj_t * ui_Roller_Number;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Roller1;
lv_obj_t * ui_Label_Steps;
lv_obj_t * ui_BTN_Reset;
lv_obj_t * ui_Label_Reset;
lv_obj_t * ui_BTN_Heat;
lv_obj_t * ui_Label_Reset1;


// SCREEN: ui_Screen_3_Setting
void ui_Screen_3_Setting_screen_init(void);
lv_obj_t * ui_Screen_3_Setting;
lv_obj_t * ui_Background2;
lv_obj_t * ui_Panel_Header2;
lv_obj_t * ui_Label_Header2;
lv_obj_t * ui_IMG_Wifi2;
lv_obj_t * ui_IMG_PC2;
lv_obj_t * ui_IMG_USB2;
void ui_event_BTN_Menu_Print_S3(lv_event_t * e);
lv_obj_t * ui_BTN_Menu_Print_S3;
void ui_event_BTN_Menu_Move_S3(lv_event_t * e);
lv_obj_t * ui_BTN_Menu_Move_S3;
lv_obj_t * ui_BTN_Menu_Setting_S3;
lv_obj_t * ui_S1_Content_Panel2;
lv_obj_t * ui_Roller_Material;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Roller4;
lv_obj_t * ui_Label_Material;
lv_obj_t * ui_Roller_Bed_Temp;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Roller3;
lv_obj_t * ui_Label_Bed_Temp1;
lv_obj_t * ui_Roller_Head_Temp;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Roller2;
lv_obj_t * ui_Label_Head_Temp1;
lv_obj_t * ui_BTN_Heat_Head;
lv_obj_t * ui_Label_Reset22;
lv_obj_t * ui_BTN_Heat_Bed;
lv_obj_t * ui_Label_Heat_Bed;
lv_obj_t * ui_BTN_Remove_Filament;
lv_obj_t * ui_Label_Remove_Filament;
lv_obj_t * ui_Panel_Slider;
void ui_event_Slider_Print_Speed(lv_event_t * e);
lv_obj_t * ui_Slider_Print_Speed;
lv_obj_t * ui_Label_Print_Speed;
lv_obj_t * ui_Label_Print_Speed_Number;
lv_obj_t * ui_Swich_Group;
lv_obj_t * ui_Label_Light;
lv_obj_t * ui_Switch_Light;
lv_obj_t * ui_Label_Fan_1;
lv_obj_t * ui_Switch_Fan_1;
lv_obj_t * ui_Label_Fan_2;
lv_obj_t * ui_Switch_Fan_2;
lv_obj_t * ui_Label_Fan_3;
lv_obj_t * ui_Switch_Fan_3;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_icn_time_[2] = {&ui_img_icn_time_1_png, &ui_img_icn_time_2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void OpaOn_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 10);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void OpaOff_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void ScreenIn_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);

}
void MenuIn_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);

}
void MenuOut_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 150);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void ScreenOut_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_BTN_Menu_Move_S1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_2_Move, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen_2_Move_screen_init);
    }
}
void ui_event_BTN_Menu_Setting_S1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_3_Setting, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen_3_Setting_screen_init);
    }
}
void ui_event_Slider_Print_View(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Number_Print, target, "", "%");
    }
}
void ui_event_BTN_Cancel_Top(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_BTN_Pause_Top, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_BTN_Menu_Print_S2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_1_Print, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen_1_Print_screen_init);
    }
}
void ui_event_BTN_Menu_Setting_S2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_3_Setting, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen_3_Setting_screen_init);
    }
}
void ui_event_GLOW_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        OpaOn_Animation(ui_GLOW_1, 0);
        _ui_state_modify(ui_Arrow_Z_up, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        OpaOff_Animation(ui_GLOW_1, 0);
        _ui_state_modify(ui_Arrow_Z_up, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_PRESS_LOST) {
        OpaOff_Animation(ui_GLOW_1, 0);
        _ui_state_modify(ui_Arrow_Z_up, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_GLOW_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        OpaOn_Animation(ui_GLOW_2, 0);
        _ui_state_modify(ui_Arrow_Z_Down, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        OpaOff_Animation(ui_GLOW_2, 0);
        _ui_state_modify(ui_Arrow_Z_Down, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_PRESS_LOST) {
        OpaOff_Animation(ui_GLOW_2, 0);
        _ui_state_modify(ui_Arrow_Z_Down, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_GLOW_3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        OpaOn_Animation(ui_GLOW_3, 0);
        _ui_state_modify(ui_Arrow_Right_2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        OpaOff_Animation(ui_GLOW_3, 0);
        _ui_state_modify(ui_Arrow_Right_2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_PRESS_LOST) {
        OpaOff_Animation(ui_GLOW_3, 0);
        _ui_state_modify(ui_Arrow_Right_2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_GLOW_4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        OpaOn_Animation(ui_GLOW_4, 0);
        _ui_state_modify(ui_Arrow_Up_2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        OpaOff_Animation(ui_GLOW_4, 0);
        _ui_state_modify(ui_Arrow_Up_2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_PRESS_LOST) {
        OpaOff_Animation(ui_GLOW_4, 0);
        _ui_state_modify(ui_Arrow_Up_2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_GLOW_5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        OpaOn_Animation(ui_GLOW_5, 0);
        _ui_state_modify(ui_Arrow_Down_2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        OpaOff_Animation(ui_GLOW_5, 0);
        _ui_state_modify(ui_Arrow_Down_2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_PRESS_LOST) {
        OpaOff_Animation(ui_GLOW_5, 0);
        _ui_state_modify(ui_Arrow_Down_2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_GLOW_6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        OpaOn_Animation(ui_GLOW_6, 0);
        _ui_state_modify(ui_Arrow_Left_2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
    if(event_code == LV_EVENT_RELEASED) {
        OpaOff_Animation(ui_GLOW_6, 0);
        _ui_state_modify(ui_Arrow_Left_2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_PRESS_LOST) {
        OpaOff_Animation(ui_GLOW_6, 0);
        _ui_state_modify(ui_Arrow_Left_2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_BTN_Menu_Print_S3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_1_Print, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen_1_Print_screen_init);
    }
}
void ui_event_BTN_Menu_Move_S3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen_2_Move, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen_2_Move_screen_init);
    }
}
void ui_event_Slider_Print_Speed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label_Print_Speed_Number, target, "", "%");
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    
    
    ui_Screen_3_Setting_screen_init();
    ui_Screen_2_Move_screen_init();
    ui_Screen_1_Print_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen_1_Print);
}
