// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: 3d_printer

#include "ui.h"

void ui_Screen_2_Move_screen_init(void)
{
    ui_Screen_2_Move = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_Screen_2_Move, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_2_Move, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Background1 = lv_img_create(ui_Screen_2_Move);
    lv_img_set_src(ui_Background1, &ui_img_3d_printer_bg_png);
    lv_obj_set_width(ui_Background1, 800);
    lv_obj_set_height(ui_Background1, 480);
    lv_obj_set_align(ui_Background1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_Panel_Header1 = lv_obj_create(ui_Screen_2_Move);
    lv_obj_set_width(ui_Panel_Header1, 665);
    lv_obj_set_height(ui_Panel_Header1, 39);
    lv_obj_set_x(ui_Panel_Header1, -30);
    lv_obj_set_y(ui_Panel_Header1, 0);
    lv_obj_set_align(ui_Panel_Header1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel_Header1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Header1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Header1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Header1 = lv_label_create(ui_Panel_Header1);
    lv_obj_set_width(ui_Label_Header1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Header1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Header1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Header1, "Press the control buttons to move the tray and head");
    lv_label_set_recolor(ui_Label_Header1, "true");
    lv_obj_set_style_text_color(ui_Label_Header1, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Header1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Header1, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_Wifi1 = lv_img_create(ui_Panel_Header1);
    lv_img_set_src(ui_IMG_Wifi1, &ui_img_icn_wifi_png);
    lv_obj_set_width(ui_IMG_Wifi1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_Wifi1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_IMG_Wifi1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_Wifi1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_IMG_PC1 = lv_img_create(ui_Panel_Header1);
    lv_img_set_src(ui_IMG_PC1, &ui_img_icn_pc_png);
    lv_obj_set_width(ui_IMG_PC1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_PC1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_PC1, -42);
    lv_obj_set_y(ui_IMG_PC1, 0);
    lv_obj_set_align(ui_IMG_PC1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_PC1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_IMG_USB1 = lv_img_create(ui_Panel_Header1);
    lv_img_set_src(ui_IMG_USB1, &ui_img_icn_usb_png);
    lv_obj_set_width(ui_IMG_USB1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_USB1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_USB1, -84);
    lv_obj_set_y(ui_IMG_USB1, 0);
    lv_obj_set_align(ui_IMG_USB1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_USB1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_BTN_Menu_Print_S2 = lv_img_create(ui_Screen_2_Move);
    lv_img_set_src(ui_BTN_Menu_Print_S2, &ui_img_btn_print_png);
    lv_obj_set_width(ui_BTN_Menu_Print_S2, 79);
    lv_obj_set_height(ui_BTN_Menu_Print_S2, 160);
    lv_obj_add_flag(ui_BTN_Menu_Print_S2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_Menu_Print_S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTN_Menu_Print_S2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Menu_Move_S2 = lv_img_create(ui_Screen_2_Move);
    lv_img_set_src(ui_BTN_Menu_Move_S2, &ui_img_btn_move_png);
    lv_obj_set_width(ui_BTN_Menu_Move_S2, 79);
    lv_obj_set_height(ui_BTN_Menu_Move_S2, 162);
    lv_obj_set_align(ui_BTN_Menu_Move_S2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTN_Menu_Move_S2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_Menu_Move_S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTN_Menu_Setting_S2 = lv_img_create(ui_Screen_2_Move);
    lv_img_set_src(ui_BTN_Menu_Setting_S2, &ui_img_btn_setting_png);
    lv_obj_set_width(ui_BTN_Menu_Setting_S2, 79);
    lv_obj_set_height(ui_BTN_Menu_Setting_S2, 160);
    lv_obj_set_align(ui_BTN_Menu_Setting_S2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BTN_Menu_Setting_S2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_Menu_Setting_S2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_BTN_Menu_Setting_S2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_S1_Content_Panel1 = lv_obj_create(ui_Screen_2_Move);
    lv_obj_set_width(ui_S1_Content_Panel1, 720);
    lv_obj_set_height(ui_S1_Content_Panel1, 430);
    lv_obj_set_align(ui_S1_Content_Panel1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_S1_Content_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_S1_Content_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_S1_Content_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_S1_Content_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display_Pos_XY = lv_obj_create(ui_S1_Content_Panel1);
    lv_obj_set_width(ui_Display_Pos_XY, 283);
    lv_obj_set_height(ui_Display_Pos_XY, 79);
    lv_obj_set_x(ui_Display_Pos_XY, 200);
    lv_obj_set_y(ui_Display_Pos_XY, 21);
    lv_obj_clear_flag(ui_Display_Pos_XY, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display_Pos_XY, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display_Pos_XY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Display_Pos_XY, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Display_Pos_XY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Display_Pos_XY, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Display_Pos_XY, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Display_Pos_XY, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Display_Pos_XY, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Display_Pos_XY, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Display_Pos_XY, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Display_Pos_XY, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Display_Pos_XY, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Display_Pos_XY, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DP1 = lv_obj_create(ui_Display_Pos_XY);
    lv_obj_set_width(ui_DP1, lv_pct(50));
    lv_obj_set_height(ui_DP1, lv_pct(100));
    lv_obj_set_align(ui_DP1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_DP1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DP1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DP1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DP1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DP1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DP1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DP1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DP1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DP1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DP1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_X_Position = lv_label_create(ui_DP1);
    lv_obj_set_width(ui_Label_X_Position, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_X_Position, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_X_Position, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_X_Position, "X Position");
    lv_label_set_recolor(ui_Label_X_Position, "true");
    lv_obj_set_style_text_color(ui_Label_X_Position, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_X_Position, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_X_Position, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_X_Position_Number = lv_label_create(ui_DP1);
    lv_obj_set_width(ui_Label_X_Position_Number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_X_Position_Number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_X_Position_Number, 0);
    lv_obj_set_y(ui_Label_X_Position_Number, 10);
    lv_obj_set_align(ui_Label_X_Position_Number, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_X_Position_Number, "185");
    lv_obj_set_style_text_color(ui_Label_X_Position_Number, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_X_Position_Number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_X_Position_Number, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Display_Pos_XY);
    lv_obj_set_width(ui_Panel2, 2);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DP2 = lv_obj_create(ui_Display_Pos_XY);
    lv_obj_set_width(ui_DP2, lv_pct(50));
    lv_obj_set_height(ui_DP2, lv_pct(100));
    lv_obj_set_align(ui_DP2, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_DP2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DP2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DP2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DP2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DP2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DP2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DP2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DP2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DP2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DP2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Y_Position = lv_label_create(ui_DP2);
    lv_obj_set_width(ui_Label_Y_Position, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Y_Position, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Y_Position, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Y_Position, "Y Position");
    lv_label_set_recolor(ui_Label_Y_Position, "true");
    lv_obj_set_style_text_color(ui_Label_Y_Position, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Y_Position, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Y_Position, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Time_3 = lv_label_create(ui_DP2);
    lv_obj_set_width(ui_Label_Time_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Time_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Time_3, 0);
    lv_obj_set_y(ui_Label_Time_3, 10);
    lv_obj_set_align(ui_Label_Time_3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Time_3, "350");
    lv_obj_set_style_text_color(ui_Label_Time_3, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Time_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Time_3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Display_Pos_y = lv_obj_create(ui_S1_Content_Panel1);
    lv_obj_set_width(ui_Display_Pos_y, 133);
    lv_obj_set_height(ui_Display_Pos_y, 79);
    lv_obj_set_x(ui_Display_Pos_y, 20);
    lv_obj_set_y(ui_Display_Pos_y, 21);
    lv_obj_clear_flag(ui_Display_Pos_y, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Display_Pos_y, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Display_Pos_y, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Display_Pos_y, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Display_Pos_y, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Display_Pos_y, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Display_Pos_y, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Display_Pos_y, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Display_Pos_y, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Display_Pos_y, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Display_Pos_y, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Display_Pos_y, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Display_Pos_y, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Display_Pos_y, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DP3 = lv_obj_create(ui_Display_Pos_y);
    lv_obj_set_width(ui_DP3, lv_pct(100));
    lv_obj_set_height(ui_DP3, lv_pct(100));
    lv_obj_set_align(ui_DP3, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_DP3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DP3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DP3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_DP3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_DP3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DP3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DP3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DP3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DP3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DP3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Z_Position = lv_label_create(ui_DP3);
    lv_obj_set_width(ui_Label_Z_Position, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Z_Position, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Z_Position, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Z_Position, "Z Position");
    lv_label_set_recolor(ui_Label_Z_Position, "true");
    lv_obj_set_style_text_color(ui_Label_Z_Position, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Z_Position, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Z_Position, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Z_Position_Number = lv_label_create(ui_DP3);
    lv_obj_set_width(ui_Label_Z_Position_Number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Z_Position_Number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Z_Position_Number, 0);
    lv_obj_set_y(ui_Label_Z_Position_Number, 10);
    lv_obj_set_align(ui_Label_Z_Position_Number, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Z_Position_Number, "350");
    lv_obj_set_style_text_color(ui_Label_Z_Position_Number, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Z_Position_Number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Z_Position_Number, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Move_Z = lv_img_create(ui_S1_Content_Panel1);
    lv_img_set_src(ui_BTN_Move_Z, &ui_img_btn_z_botton_png);
    lv_obj_set_width(ui_BTN_Move_Z, 140);
    lv_obj_set_height(ui_BTN_Move_Z, 312);
    lv_obj_set_x(ui_BTN_Move_Z, -273);
    lv_obj_set_y(ui_BTN_Move_Z, 45);
    lv_obj_set_align(ui_BTN_Move_Z, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Move_Z, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_GLOW_1 = lv_obj_create(ui_BTN_Move_Z);
    lv_obj_set_width(ui_GLOW_1, 75);
    lv_obj_set_height(ui_GLOW_1, 70);
    lv_obj_set_x(ui_GLOW_1, 0);
    lv_obj_set_y(ui_GLOW_1, 34);
    lv_obj_set_align(ui_GLOW_1, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_GLOW_1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GLOW_1, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GLOW_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_GLOW_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_GLOW_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GLOW_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_GLOW_1, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_GLOW_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_GLOW_1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_GLOW_1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_GLOW_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GLOW_2 = lv_obj_create(ui_BTN_Move_Z);
    lv_obj_set_width(ui_GLOW_2, 75);
    lv_obj_set_height(ui_GLOW_2, 70);
    lv_obj_set_x(ui_GLOW_2, 0);
    lv_obj_set_y(ui_GLOW_2, 211);
    lv_obj_set_align(ui_GLOW_2, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_GLOW_2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GLOW_2, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GLOW_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_GLOW_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_GLOW_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GLOW_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_GLOW_2, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_GLOW_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_GLOW_2, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_GLOW_2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_GLOW_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Image_Top = lv_img_create(ui_BTN_Move_Z);
    lv_img_set_src(ui_BTN_Image_Top, &ui_img_btn_z_top_png);
    lv_obj_set_width(ui_BTN_Image_Top, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTN_Image_Top, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_BTN_Image_Top, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Image_Top, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_Label_Z_Position_2 = lv_label_create(ui_BTN_Image_Top);
    lv_obj_set_width(ui_Label_Z_Position_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Z_Position_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Z_Position_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Z_Position_2, "MOVE\nZ");
    lv_label_set_recolor(ui_Label_Z_Position_2, "true");
    lv_obj_set_style_text_color(ui_Label_Z_Position_2, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Z_Position_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Z_Position_2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Z_Position_2, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arrow_Z_up = lv_img_create(ui_BTN_Image_Top);
    lv_img_set_src(ui_Arrow_Z_up, &ui_img_arrow_up_png);
    lv_obj_set_width(ui_Arrow_Z_up, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Arrow_Z_up, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Arrow_Z_up, 0);
    lv_obj_set_y(ui_Arrow_Z_up, 20);
    lv_obj_set_align(ui_Arrow_Z_up, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Arrow_Z_up, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_img_recolor(ui_Arrow_Z_up, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Arrow_Z_up, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_up, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor(ui_Arrow_Z_up, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_up, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Arrow_Z_Down = lv_img_create(ui_BTN_Image_Top);
    lv_img_set_src(ui_Arrow_Z_Down, &ui_img_arrow_down_png);
    lv_obj_set_width(ui_Arrow_Z_Down, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Arrow_Z_Down, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Arrow_Z_Down, 0);
    lv_obj_set_y(ui_Arrow_Z_Down, -20);
    lv_obj_set_align(ui_Arrow_Z_Down, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Arrow_Z_Down, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_img_recolor(ui_Arrow_Z_Down, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_Down, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Arrow_Z_Down, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_Down, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_BTN_Move_XY = lv_img_create(ui_S1_Content_Panel1);
    lv_img_set_src(ui_BTN_Move_XY, &ui_img_btn_pad_bottom_png);
    lv_obj_set_width(ui_BTN_Move_XY, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTN_Move_XY, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_BTN_Move_XY, -15);
    lv_obj_set_y(ui_BTN_Move_XY, 40);
    lv_obj_set_align(ui_BTN_Move_XY, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Move_XY, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_GLOW_3 = lv_obj_create(ui_BTN_Move_XY);
    lv_obj_set_width(ui_GLOW_3, 120);
    lv_obj_set_height(ui_GLOW_3, 120);
    lv_obj_set_x(ui_GLOW_3, 64);
    lv_obj_set_y(ui_GLOW_3, 97);
    lv_obj_set_align(ui_GLOW_3, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_GLOW_3, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GLOW_3, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GLOW_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_GLOW_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_GLOW_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GLOW_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_GLOW_3, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_GLOW_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_GLOW_3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_GLOW_3, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_GLOW_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GLOW_4 = lv_obj_create(ui_BTN_Move_XY);
    lv_obj_set_width(ui_GLOW_4, 120);
    lv_obj_set_height(ui_GLOW_4, 120);
    lv_obj_set_x(ui_GLOW_4, 1);
    lv_obj_set_y(ui_GLOW_4, 33);
    lv_obj_set_align(ui_GLOW_4, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_GLOW_4, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GLOW_4, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GLOW_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_GLOW_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_GLOW_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GLOW_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_GLOW_4, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_GLOW_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_GLOW_4, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_GLOW_4, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_GLOW_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GLOW_5 = lv_obj_create(ui_BTN_Move_XY);
    lv_obj_set_width(ui_GLOW_5, 120);
    lv_obj_set_height(ui_GLOW_5, 120);
    lv_obj_set_x(ui_GLOW_5, 0);
    lv_obj_set_y(ui_GLOW_5, 158);
    lv_obj_set_align(ui_GLOW_5, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_GLOW_5, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GLOW_5, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GLOW_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_GLOW_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_GLOW_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GLOW_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_GLOW_5, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_GLOW_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_GLOW_5, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_GLOW_5, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_GLOW_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GLOW_6 = lv_obj_create(ui_BTN_Move_XY);
    lv_obj_set_width(ui_GLOW_6, 120);
    lv_obj_set_height(ui_GLOW_6, 120);
    lv_obj_set_x(ui_GLOW_6, -64);
    lv_obj_set_y(ui_GLOW_6, 96);
    lv_obj_set_align(ui_GLOW_6, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_GLOW_6, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GLOW_6, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GLOW_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_GLOW_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_GLOW_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GLOW_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_GLOW_6, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_GLOW_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_GLOW_6, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_GLOW_6, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_GLOW_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Move_XY_Top = lv_img_create(ui_BTN_Move_XY);
    lv_img_set_src(ui_BTN_Move_XY_Top, &ui_img_btn_pad_top_png);
    lv_obj_set_width(ui_BTN_Move_XY_Top, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTN_Move_XY_Top, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_BTN_Move_XY_Top, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Move_XY_Top, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_img_set_pivot(ui_BTN_Move_XY_Top, 121, 118);

    ui_Label_XY_Position = lv_label_create(ui_BTN_Move_XY_Top);
    lv_obj_set_width(ui_Label_XY_Position, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_XY_Position, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_XY_Position, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_XY_Position, "MOVE\nXY");
    lv_label_set_recolor(ui_Label_XY_Position, "true");
    lv_obj_set_style_text_color(ui_Label_XY_Position, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_XY_Position, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_XY_Position, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_XY_Position, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arrow_Up_2 = lv_img_create(ui_BTN_Move_XY_Top);
    lv_img_set_src(ui_Arrow_Up_2, &ui_img_arrow_up_png);
    lv_obj_set_width(ui_Arrow_Up_2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Arrow_Up_2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Arrow_Up_2, 0);
    lv_obj_set_y(ui_Arrow_Up_2, 25);
    lv_obj_set_align(ui_Arrow_Up_2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Arrow_Up_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_img_recolor(ui_Arrow_Up_2, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Arrow_Up_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Arrow_Up_2, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_Arrow_Up_2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Arrow_Down_2 = lv_img_create(ui_BTN_Move_XY_Top);
    lv_img_set_src(ui_Arrow_Down_2, &ui_img_arrow_down_png);
    lv_obj_set_width(ui_Arrow_Down_2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Arrow_Down_2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Arrow_Down_2, 0);
    lv_obj_set_y(ui_Arrow_Down_2, -25);
    lv_obj_set_align(ui_Arrow_Down_2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Arrow_Down_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_img_recolor(ui_Arrow_Down_2, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Arrow_Down_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Arrow_Down_2, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_Arrow_Down_2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Arrow_Left_2 = lv_img_create(ui_BTN_Move_XY_Top);
    lv_img_set_src(ui_Arrow_Left_2, &ui_img_arrow_left_png);
    lv_obj_set_width(ui_Arrow_Left_2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Arrow_Left_2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Arrow_Left_2, 25);
    lv_obj_set_y(ui_Arrow_Left_2, 0);
    lv_obj_set_align(ui_Arrow_Left_2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Arrow_Left_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_img_recolor(ui_Arrow_Left_2, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Arrow_Left_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Arrow_Left_2, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_Arrow_Left_2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Arrow_Right_2 = lv_img_create(ui_BTN_Move_XY_Top);
    lv_img_set_src(ui_Arrow_Right_2, &ui_img_arrow_right_png);
    lv_obj_set_width(ui_Arrow_Right_2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Arrow_Right_2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Arrow_Right_2, -25);
    lv_obj_set_y(ui_Arrow_Right_2, 0);
    lv_obj_set_align(ui_Arrow_Right_2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Arrow_Right_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_set_style_img_recolor(ui_Arrow_Right_2, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Arrow_Right_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Arrow_Right_2, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_Arrow_Right_2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Roller_Number = lv_obj_create(ui_S1_Content_Panel1);
    lv_obj_set_height(ui_Roller_Number, 215);
    lv_obj_set_width(ui_Roller_Number, LV_SIZE_CONTENT);   /// 165
    lv_obj_set_x(ui_Roller_Number, 238);
    lv_obj_set_y(ui_Roller_Number, 86);
    lv_obj_set_align(ui_Roller_Number, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Roller_Number, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Roller_Number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller_Number, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Roller_Number, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Roller_Number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Roller_Number, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Roller_Number, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Roller_Number, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Roller_Number, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Roller_Number, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_Roller_Number);
    lv_img_set_src(ui_Image8, &ui_img_roller_bg_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags

    ui_Roller1 = lv_roller_create(ui_Roller_Number);
    lv_roller_set_options(ui_Roller1, "1\n5\n10\n15\n25\n50", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Roller1, 142);
    lv_obj_set_height(ui_Roller1, 131);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Roller1, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller1, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Roller1, lv_color_hex(0xDBE6FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller1, &lv_font_montserrat_26, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x3A445C), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label_Steps = lv_label_create(ui_Roller_Number);
    lv_obj_set_width(ui_Label_Steps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Steps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Steps, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Steps, "STEPS SIZE");
    lv_label_set_recolor(ui_Label_Steps, "true");
    lv_obj_set_style_text_color(ui_Label_Steps, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Steps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Steps, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Steps, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Reset = lv_imgbtn_create(ui_S1_Content_Panel1);
    lv_imgbtn_set_src(ui_BTN_Reset, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Reset, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Reset, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Reset, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_BTN_Reset, 66);
    lv_obj_set_width(ui_BTN_Reset, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_BTN_Reset, -40);
    lv_obj_set_y(ui_BTN_Reset, 20);
    lv_obj_set_align(ui_BTN_Reset, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_text_color(ui_BTN_Reset, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTN_Reset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTN_Reset, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_BTN_Reset, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_BTN_Reset, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_BTN_Reset, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label_Reset = lv_label_create(ui_BTN_Reset);
    lv_obj_set_width(ui_Label_Reset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Reset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Reset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Reset, "RESET POS.");
    lv_label_set_recolor(ui_Label_Reset, "true");
    lv_obj_set_style_text_align(ui_Label_Reset, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Reset, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Heat = lv_imgbtn_create(ui_S1_Content_Panel1);
    lv_imgbtn_set_src(ui_BTN_Heat, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Heat, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Heat, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_imgbtn_set_src(ui_BTN_Heat, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
    lv_obj_set_height(ui_BTN_Heat, 66);
    lv_obj_set_width(ui_BTN_Heat, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_BTN_Heat, -40);
    lv_obj_set_y(ui_BTN_Heat, 100);
    lv_obj_set_align(ui_BTN_Heat, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_BTN_Heat, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_BTN_Heat, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTN_Heat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BTN_Heat, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_BTN_Heat, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_BTN_Heat, lv_color_hex(0x00D1FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_BTN_Heat, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label_Reset1 = lv_label_create(ui_BTN_Heat);
    lv_obj_set_width(ui_Label_Reset1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Reset1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Reset1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Reset1, "HEAT");
    lv_label_set_recolor(ui_Label_Reset1, "true");
    lv_obj_set_style_text_align(ui_Label_Reset1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Reset1, &ui_font_Small_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BTN_Menu_Print_S2, ui_event_BTN_Menu_Print_S2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTN_Menu_Setting_S2, ui_event_BTN_Menu_Setting_S2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GLOW_1, ui_event_GLOW_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GLOW_2, ui_event_GLOW_2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GLOW_3, ui_event_GLOW_3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GLOW_4, ui_event_GLOW_4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GLOW_5, ui_event_GLOW_5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GLOW_6, ui_event_GLOW_6, LV_EVENT_ALL, NULL);

}
