// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: UWB_Measure

#ifndef _UWB_MEASURE_UI_H
#define _UWB_MEASURE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_BG;
extern lv_obj_t *ui_contentText;
extern lv_obj_t *ui_Spinner;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( BG_Image);   // assets/BG_Image.png

LV_FONT_DECLARE( ui_font_Bold60);
LV_FONT_DECLARE( ui_font_Regular50);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
