// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: UWB_Measure

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BG = lv_img_create(ui_Screen1);
lv_img_set_src(ui_BG, &BG_Image);
lv_obj_set_width( ui_BG, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BG, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BG, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BG, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_contentText = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_contentText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_contentText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_contentText, -16 );
lv_obj_set_y( ui_contentText, 32 );
lv_obj_set_align( ui_contentText, LV_ALIGN_CENTER );
lv_label_set_text(ui_contentText,"...");
lv_obj_set_style_text_font(ui_contentText, &ui_font_Bold60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner = lv_spinner_create(ui_Screen1,1000,90);
lv_obj_set_width( ui_Spinner, 30);
lv_obj_set_height( ui_Spinner, 30);
lv_obj_set_x( ui_Spinner, -60 );
lv_obj_set_y( ui_Spinner, -10 );
lv_obj_set_align( ui_Spinner, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_clear_flag( ui_Spinner, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_Spinner, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Spinner, lv_color_hex(0xF6BA00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Spinner, 60, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Spinner, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

}
