// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: Turntable

#ifndef _TURNTABLE_UI_H
#define _TURNTABLE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include <lvgl.h>

#include "ui_events.h"
void RecordAnim_Animation( lv_obj_t *TargetObject, int delay);
void HandAnim_Animation( lv_obj_t *TargetObject, int delay);
void RecordAnim2_Animation( lv_obj_t *TargetObject, int delay);
void HandAnimOff_Animation( lv_obj_t *TargetObject, int delay);
void RecordAnimOff_Animation( lv_obj_t *TargetObject, int delay);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_RootPanel;
extern lv_obj_t *ui_Background;
extern lv_obj_t *ui_Volume;
extern lv_obj_t *ui_VolumeArc;
extern lv_obj_t *ui_Record;
extern lv_obj_t *ui_Hand;
extern lv_obj_t *ui_PowerButton;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_bg_png);   // assets/bg.png
LV_IMG_DECLARE( ui_img_vol_switch_png);   // assets/vol_switch.png
LV_IMG_DECLARE( ui_img_turntable_png);   // assets/turntable.png
LV_IMG_DECLARE( ui_img_hand_png);   // assets/hand.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
